name: MVanish
version: '${project.version}'
main: mvanish.mvanish.Main
api-version: 1.16
softdepend: [PlaceholderAPI, ProtocolLIB]
commands:
  vanish:
    usage: /<command>
    aliases:
      - v

  unvanish:
    usage: /<command>
    aliases:
      - uv

  vanish-about:
    usage: /<command>
    aliases:
      - aboutvanish


  vanish-other:
    usage: /<commands>
    aliases:
      - vother
      - vanishother

  unvanish-other:
    usage: /<command>
    aliases:
      - uv-other
      - unvanishother
      - uvother
